# Generated by Django 2.2.13 on 2020-08-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('startdate', models.DateField(auto_now=True)),
                ('enddate', models.DateField(auto_now=True)),
                ('duration', models.DateField(null=True)),
            ],
        ),
    ]
