# Generated by Django 2.2.13 on 2020-08-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
    ]
