# Generated by Django 2.2.13 on 2020-08-07 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='photo',
            field=models.ImageField(null=True, upload_to='static'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('startdate', models.DateField(auto_now=True)),
                ('enddate', models.DateField(auto_now=True)),
                ('duration', models.IntegerField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Projects')),
            ],
        ),
    ]
