# Generated by Django 2.2.13 on 2020-08-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200807_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='asign_to',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
