# Generated by Django 2.2.13 on 2020-08-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_task_asign_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.IntegerField(null=True),
        ),
    ]
